name: 'mal_analytics'
version: '1.0.0'
config-version: 2

profile: 'mal_analytics_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mal_analytics:
    bronze:
      +materialized: view
    silver:
      +materialized: table